FROM mosaicml/llm-foundry:2.6.0_cu124-latest

LABEL maintainer="Greg Gandenberger <gsganden@gmail.com>"
LABEL description="Development environment for LLM-Foundry"

WORKDIR /llm-foundry

RUN apt-get update \
    && apt-get install -y \
    wget \
    git \
    && rm -rf /var/lib/apt/lists/*

# Create directory for Hugging Face token and declare it as a volume
RUN mkdir -p /root/.cache/huggingface
VOLUME /root/.cache/huggingface
