FROM mosaicml/llm-foundry:2.6.0_cu124-latest
# COPY --from=ghcr.io/astral-sh/uv:0.6.5 /uv /uvx /bin/

LABEL maintainer="Greg Gandenberger <gsganden@gmail.com>"
LABEL description="Development environment for LLM-Foundry"

WORKDIR /llm-foundry

RUN apt-get update \
    && apt-get install -y \
    wget \
    git \
    && rm -rf /var/lib/apt/lists/*

ADD . /llm-foundry
RUN --mount=type=cache,target=/root/.cache/uv \
    # uv venv --python 3.11.4 \
    # && source .venv/bin/activate \
    # && uv pip install -e .
    pip install -e .

RUN mkdir -p /root/.cache/huggingface
VOLUME /root/.cache/huggingface

# ENV PATH="/workspaces/llm-foundry/.venv/bin:$PATH"
