name: PyTest Coverage
on:
  workflow_call:
    inputs:
      download-path:
        required: true
        type: string
jobs:
  coverage:
    timeout-minutes: 5
    runs-on: linux-ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Get composite run steps repository
      uses: actions/checkout@v3
      with:
        repository: mosaicml/ci-testing
        ref: 66add21924188cc1244bbd2c661dc760d7389894
        path: ./ci-testing
    - uses: ./ci-testing/.github/actions/coverage
      with:
        download-path: ${{ inputs.download-path }}
